version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase-functions
    versions:
    - 3.13.1
  - dependency-name: lodash
    versions:
    - 4.17.20
